### ISSUE TITLE
event_db_index01

### ISSUE THREAD

**Issue by rorylasting** [RANSoftware/Hikvision-PIC-to-JPG#1]
Hello, thanks for the great script! A real life saver as Hikvision's tech support was no help! I originally posted the following error message on your YouTube channel. You replied with an update to the script that fixed the issue I was having. I tried sharing the Google Drive link to the event_db_index01 file, but YouTube deleted the comment, so I uploaded the file here.

**__Processing folder: C:/Users/rlasting/Desktop/Hikvison/datadir0

*** event_id found ***

Number of tables in database: 32

*** certificateRevocationTable found ***
DBD::SQLite::db prepare failed: no such column: pic_offset_0 at C:\Users\rlasting\Desktop\Hikvison\extract_capture.pl line 228, <STDIN> line 4.
DBD::SQLite::db prepare failed: no such column: pic_offset_0 at C:\Users\rlasting\Desktop\Hikvison\extract_capture.pl line 228, <STDIN> line 4.
Processing table: certificateRevocationTable:__**

[event_db_index01.zip](https://github.com/RANSoftware/Hikvision-PIC-to-JPG/files/13795305/event_db_index01.zip)

**Comment by RANSoftware** [comment]
Hi, I've updated the script and it should work now. The issue was caused by the script attempting to process the certificateRevocationTable, which did not contain any information about the images.

Thank you for providing the event_db_index01 file. It not only helped me fix the above issue, but also allowed me to update the predefined detection tables (Hikvision changed some of the names).
